### ISSUE TITLE
[tracking] upload Beta release to Quay and setup updates

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#118]
Ensure builds from `4.4.0-0.okd` stream get promoted weekly to `4-stable` and get uploaded to quay.

TODO:
* [x] Promote a nightly and mirror to quay
* [x] Tag build into `stable-4`
* [x] Ensure betas appear in the release controller's graph
* [x] Upload new beta as a github release

**Comment by vrutkovs** [comment]
Ah, apparently this is still a manual action for now. Changing this ticket to Beta upload and updates testing

**Comment by vrutkovs** [comment]
Beta 1 uploaded to quay, nightlies update setup.

The remaining issue is adding quay image to `stable-4`
