### ISSUE TITLE
[tracking] Switch 4.6 to stable stream once F33 content lands

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#383]
TODO:
* [x] Update `okd-machine-os` to use stable stream in F33
* [ ] Update 4.6 promotion periodics to run daily
* [ ] Update 4.7 promotion periodics to run every 4 hours
