### ISSUE TITLE
[tracking] next 4.6 stable release

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#422]
Issues fixed:
* [ ] https://github.com/openshift/okd/issues/416
* [ ] https://github.com/openshift/okd/issues/380
* [ ] https://github.com/openshift/okd/issues/401
* [ ] https://github.com/openshift/okd/issues/126
* [ ] https://github.com/openshift/okd/issues/394
* [ ] https://github.com/openshift/okd/issues/407
* [ ] https://github.com/openshift/okd/issues/392

Notable unresolved issues:
* [ ] https://github.com/openshift/okd/issues/402
  This requires fix landing on buildfarm and image rebuild. Critical for image mirroring
* [ ] https://github.com/openshift/okd/issues/398
  Seems to be affecting proxy setups. Make sure all repos on hosts are disabled or have valid proxy configs added
* [ ] https://github.com/openshift/okd/issues/405
  OVN seems to be using more CPU than it used to on 4.5. Needs bugzilla
* [ ] https://github.com/openshift/okd/issues/395
  openshift-apiserver may hang up during upgrade

**Comment by vrutkovs** [comment]
https://amd64.origin.releases.ci.openshift.org/releasestream/4-stable/release/4.6.0-0.okd-2020-12-12-135354
https://github.com/openshift/okd/releases/tag/4.6.0-0.okd-2020-12-12-135354

**Comment by fortinj66** [comment]
Worked seemlessly...  Closing 407

https://github.com/openshift/okd/issues/407

**Comment by fortinj66** [comment]
4.5->4.6 - Upgrade completed successfully with no observed issues
